import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { MyNavbar } from '@/components/navbar';
import { MyFooter } from '@/components/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <main className="flex-1">
            <MyNavbar />
              {children}
          </main>
          <MyFooter />
        </div>
      </body>
    </html>
  )
}